const mongoose = require("mongoose");
const { Schema } = mongoose;

// ─── Generator Output ─────────────────────────────────────────────────────────
// Whatever MissionGenerator produced — same shape for all generation modes.
// Now includes all point data from GeneratePoints.js.

const GeneratorSchema = new Schema(
	{
		generationMode: {
			type: String,
			enum: ["random", "ops"],
			default: "random",
		},
		selectedLocations: { type: [Schema.Types.Mixed], default: [] },
		mapBounds: { type: Schema.Types.Mixed },
		imgURL: { type: String, default: "" },

		// Mission type — stored here so generator and briefing share it
		missionType: { type: String, default: "" },

		// Insertion/extraction points — [row, col] pixel arrays
		// Set by GeneratePoints.js (algorithmic — no AI)
		infilPoint: { type: Schema.Types.Mixed, default: null },
		exfilPoint: { type: Schema.Types.Mixed, default: null },
		rallyPoint: { type: Schema.Types.Mixed, default: null },

		// Approach metadata from GeneratePoints.js
		infilMethod: { type: String, default: "" },
		exfilMethod: { type: String, default: "" },
		approachVector: { type: String, default: "" },
	},
	{ _id: false },
);

// ─── Generator Snapshot ───────────────────────────────────────────────────────
// Point-in-time copy of insertion points at the time a phase was played.
// Stored on each Phase so the AAR has accurate coordinates even if the
// player regenerates points for a new mission later.

const GeneratorSnapshotSchema = new Schema(
	{
		infilPoint: { type: Schema.Types.Mixed, default: null },
		exfilPoint: { type: Schema.Types.Mixed, default: null },
		rallyPoint: { type: Schema.Types.Mixed, default: null },
		infilMethod: { type: String, default: "" },
		exfilMethod: { type: String, default: "" },
	},
	{ _id: false },
);

// ─── Phase ────────────────────────────────────────────────────────────────────
// One completed post-mission phase report filed via PhaseReportSheet.
// Multiple phases per operation, ordered by phaseNumber.

const PhaseSchema = new Schema(
	{
		phaseNumber: { type: Number, required: true },

		// Context snapshot — province and mission type at time of play
		province: { type: String, default: "" },
		missionType: { type: String, default: "" },

		// Objectives active during this phase (location names)
		objectives: { type: [String], default: [] },

		// Screen 1 — Outcome (single select)
		outcome: {
			type: String,
			enum: [
				"clean",
				"compromised",
				"heavy_contact",
				"aborted",
				"target_not_present",
			],
			required: true,
		},

		// Screen 2 — Complications (multi-select)
		complications: {
			type: [String],
			enum: [
				"none",
				"qrf_responded",
				"isr_offline",
				"crosscom_lost",
				"exfil_compromised",
				"civilian_contact",
				"intel_recovered",
				"target_not_found",
				"asset_lost",
			],
			default: [],
		},

		// Screen 3 — Casualties
		casualties: {
			type: String,
			enum: ["none", "injured", "kia"],
			required: true,
		},
		casualtyNote: { type: String, default: "", maxlength: 150 },

		// Screen 4 — Intel developed (multi-select)
		intelDeveloped: {
			type: [String],
			enum: [
				"nothing_new",
				"patrol_timing",
				"enemy_strength",
				"facility_layout",
				"hvt_location",
				"supply_route",
				"contact_activated",
			],
			default: [],
		},

		// Screen 4 — Optional field notes
		notes: { type: String, default: "", maxlength: 150 },

		// Snapshot of insertion points at time of play
		generatorSnapshot: { type: GeneratorSnapshotSchema, default: () => ({}) },

		createdAt: { type: Date, default: Date.now },
	},
	{ timestamps: false },
);

// ─── Mission ──────────────────────────────────────────────────────────────────

const MissionSchema = new Schema(
	{
		// Auth — Cognito sub or username
		createdBy: { type: String, required: true, index: true },

		// Identity
		name: { type: String, required: true, trim: true, maxlength: 80 },
		status: {
			type: String,
			enum: ["planning", "active", "complete"],
			default: "planning",
		},

		// Province / biome — top-level so mission list can display without
		// unpacking the generator sub-document
		province: { type: String, default: "" },
		biome: { type: String, default: "" },

		// Mission Generator output — set by MissionGenerator.jsx via saveMissionGenerator()
		generator: { type: GeneratorSchema, default: () => ({}) },

		// Briefing text — generated by BriefingGenerator.js (pure function, no AI)
		briefingText: { type: String, default: "" },

		// Phase reports — appended one at a time via POST /missions/:id/phases
		phases: { type: [PhaseSchema], default: [] },

		// After Action Report — generated by generateAAR() (single Groq call)
		// null until first AAR is generated and saved
		aar: { type: String, default: null },

		// Player scratchpad
		notes: { type: String, default: "", maxlength: 2000 },
	},
	{
		timestamps: true, // adds createdAt + updatedAt
	},
);

// ─── Indexes ──────────────────────────────────────────────────────────────────

MissionSchema.index({ createdBy: 1, createdAt: -1 });

module.exports = mongoose.model("Mission", MissionSchema);
